apiVersion: v1
kind: Service
metadata:
  labels:
    servicedeepsignal: ds-rm-recommendation
  name: ds-rm-recommendation
  namespace: ds-ns-rm-recommendation
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 32230
    targetPort: 8088
  selector:
    app: ds-rm-recommendation
  sessionAffinity: None
  type: LoadBalancer