apiVersion: v1
kind: Service
metadata:
  labels:
    servicedeepsignal: ds-rm-qa
  name: ds-rm-qa-service-headless
  namespace: ds-ns-rm-qa
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-ds-api
    port: 80
    protocol: TCP
    targetPort: 8088
  selector:
    app: ds-rm-qa
  sessionAffinity: None
  publishNotReadyAddresses: true
  type: ClusterIP