apiVersion: v1
kind: Service
metadata:
  labels:
    servicedeepsignal: ds-test
  name: ds-test-service
  namespace: ds-ns
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 32229
    targetPort: 8088
  selector:
    app: ds-test
  sessionAffinity: None
  type: LoadBalancer