apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    cloud.google.com/neg-status: '{"network_endpoint_groups":{"80":"k8s1-41abc7a7-ds-ns-ds-test-service-80-19c5603c"},"zones":["us-central1-c"]}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"servicedeepsignal":"ds-test"},"name":"ds-test-service","namespace":"ds-ns"},"spec":{"ports":[{"port":80,"targetPort":8088}],"selector":{"app":"ds-test"},"sessionAffinity":"None","type":"LoadBalancer"}}
  creationTimestamp: "2022-02-23T09:03:17Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    servicedeepsignal: ds-test
  name: ds-test-service-headless
  namespace: ds-ns
  resourceVersion: "28201833"
  uid: 592fd08f-8781-463c-9006-9449b4be287f
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-ds-api
    port: 80
    protocol: TCP
    targetPort: 8088
  selector:
    app: ds-test
  sessionAffinity: None
  publishNotReadyAddresses: true
  type: ClusterIP