apiVersion: v1
kind: Service
metadata:
  labels:
    servicedeepsignal: ds-rm-recommendation
  name: ds-rm-recommendation-service-headless
  namespace: ds-ns-rm-recommendation
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-ds-api
    port: 80
    protocol: TCP
    targetPort: 8088
  selector:
    app: ds-rm-recommendation
  sessionAffinity: None
  publishNotReadyAddresses: true
  type: ClusterIP