apiVersion: v1
kind: Service
metadata:
  labels:
    servicedeepsignal: ds-rm-qa
  name: ds-rm-qa
  namespace: ds-ns-rm-qa
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 32235
    targetPort: 8088
  selector:
    app: ds-rm-qa
  sessionAffinity: None
  type: LoadBalancer